---
# tasks file for master-instance
- ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        count: 1
        instance_type: t2.micro
        image: ami-0e2e44c03b85f58b3
        group_id: sg-040402e1934f83539
        region: ap-southeast-1
        instance_tags: '{"Name":"k8s_master_an"}'
        wait: yes
        key_name: Your_key_name
# Replace key_name, group_id as security group id, region as per your requirement        
 
